CREATE TABLE IF NOT EXISTS strategic_foundations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,

    business_name VARCHAR(190) NOT NULL DEFAULT '',
    first_name VARCHAR(120) NOT NULL DEFAULT '',
    last_name VARCHAR(120) NOT NULL DEFAULT '',
    role_title VARCHAR(190) NOT NULL DEFAULT '',
    primary_city VARCHAR(120) NOT NULL DEFAULT '',
    service_area VARCHAR(255) NOT NULL DEFAULT '',
    target_client_type VARCHAR(255) NOT NULL DEFAULT '',
    primary_contacts TEXT NULL,
    website_url VARCHAR(255) NOT NULL DEFAULT '',
    social_links TEXT NULL,

    who_i_help TEXT NULL,
    main_problem_solved TEXT NULL,
    target_persona TEXT NULL,
    differentiator TEXT NULL,
    why_choose_me TEXT NULL,
    what_i_do_not_do TEXT NULL,
    communication_tone TEXT NULL,

    core_promise TEXT NULL,
    promised_transformation TEXT NULL,
    core_benefits TEXT NULL,
    expected_result TEXT NULL,
    promise_timeline VARCHAR(190) NOT NULL DEFAULT '',
    short_promise_phrase VARCHAR(255) NOT NULL DEFAULT '',
    long_promise_version TEXT NULL,

    offer_name VARCHAR(255) NOT NULL DEFAULT '',
    offer_subtitle VARCHAR(255) NOT NULL DEFAULT '',
    offer_for_who TEXT NULL,
    offer_problem TEXT NULL,
    offer_content TEXT NULL,
    offer_steps TEXT NULL,
    offer_deliverables TEXT NULL,
    offer_bonus TEXT NULL,
    offer_guarantee TEXT NULL,
    offer_price VARCHAR(120) NOT NULL DEFAULT '',
    offer_terms TEXT NULL,
    offer_common_objections TEXT NULL,
    offer_objection_answers TEXT NULL,
    offer_primary_cta TEXT NULL,

    testimonials TEXT NULL,
    results_obtained TEXT NULL,
    experience_text TEXT NULL,
    certifications TEXT NULL,
    method_process TEXT NULL,
    values_text TEXT NULL,
    reassurance_elements TEXT NULL,

    send_email VARCHAR(190) NOT NULL DEFAULT '',
    email_signature TEXT NULL,
    sender_display_name VARCHAR(190) NOT NULL DEFAULT '',
    primary_domain VARCHAR(190) NOT NULL DEFAULT '',
    desired_public_url VARCHAR(255) NOT NULL DEFAULT '',
    production_main_cta TEXT NULL,
    booking_link VARCHAR(255) NOT NULL DEFAULT '',
    whatsapp_link VARCHAR(255) NOT NULL DEFAULT '',
    download_link VARCHAR(255) NOT NULL DEFAULT '',
    internal_strategy_notes TEXT NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY uq_strategic_foundation_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS public_pages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) NOT NULL DEFAULT '',
    slug VARCHAR(190) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    body_html MEDIUMTEXT NULL,
    source_snapshot_json LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    published_at DATETIME NULL,

    UNIQUE KEY uq_public_page_slug (slug),
    KEY idx_public_pages_user (user_id),
    KEY idx_public_pages_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
